config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :create]

  namespace :teacher do
    resources :homeworks do
      resources :assignments, only: [:create, :show]
    end
  end

  namespace :student do
    resources :assignments, only: [:index] do
      resources :answers, only: [:new, :create]
    end
  end

  root 'teacher/homeworks#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]
end

app/models/homework.rb
# == Schema Information
#
# Table name: homeworks
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  question   :text             not null
#  due_at     :datetime         not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Homework < ActiveRecord::Base
  belongs_to :teacher, class_name: "User", foreign_key: "user_id"
  has_many :assignments

  validates :title, :question, :due_at, presence: true

  def expired?
    due_at.end_of_day < Time.current
  end
end

app/controllers/student/homeworks_controller.rb
class Student::HomeworksController < ApplicationController

  before_action :authenticate_student!

  def index
    @current_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at >= ?", Date.current.end_of_day)
    @past_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at < ?", Date.current.end_of_day)
  end
end

app/controllers/teacher/assignments_controller.rb
class Teacher::AssignmentsController < ApplicationController

  before_action :authenticate_teacher!

  def show
    @assignment = current_teacher.homeworks.find(params[:homework_id]).assignments.find(params[:id])
  end

  def create
    @homework = current_teacher.homeworks.find(params[:homework_id])
 
    @assignment = @homework.assignments.new(assignment_params)

    if @assignment.save
      flash[:notice] = "Student successfully assigned to homework"
      redirect_to teacher_homework_path(@homework)
    else
      render :new
    end
  end

  private

    def assignment_params
      params.require(:assignment).permit(:user_id)
    end
end

app/controllers/teacher/homeworks_controller.rb
class Teacher::HomeworksController < ApplicationController

  before_action :authenticate_teacher!

  def index
    @current_homeworks = current_teacher.homeworks.where("due_at::date >= ?", Date.current)
    @past_homeworks = current_teacher.homeworks.where("due_at::date < ?", Date.current)
  end

  def new
    @homework = Homework.new
  end

  def show
    @homework = current_teacher.homeworks.find(params[:id])
    @assignments = @homework.assignments.includes(:student, :answers)
    @unassigned_students = User.student.where.not(id: @homework.assignments.pluck(:user_id))
  end

  def create
    @homework = current_teacher.homeworks.new(homework_params)
 
    if @homework.save
      flash[:notice] = "Homework created. Go ahead and assign it to students now"
      redirect_to teacher_homework_path(@homework)
    else
      render :new
    end
  end

  private

    def homework_params
      params.require(:homework).permit(:title, :question, :due_at)
    end
end

app/views/teacher/homeworks/index.html.erb
<%= render partial: "shared/flash_messages", flash: flash %>

<div class="panel panel-default">
  <div class="panel-heading">
    Current homeworks <span class="pull-right"><%= link_to "create new homework", new_teacher_homework_path %></span>
  </div>

  <% if @current_homeworks.empty? %>
    <div class="panel-body">
      <h4 class="empty-state">Uow, you don't have any homeworks to assign to your students. Why don't you <%= link_to "give it a try?", new_teacher_homework_path %></h4>
    </div>
  <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Homework</th>
          <th>Due date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @current_homeworks.each do |homework| %>
          <tr>
            <td><%= homework.title %></td>
            <td><%= homework.due_at.strftime("%m-%d-%Y") %></td>
            <td><%= link_to "view", teacher_homework_path(homework) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<% unless @past_homeworks.empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      Past homeworks
    </div>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Homework</th>
            <th>Due date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @past_homeworks.each do |homework| %>
            <tr>
              <td><%= homework.title %></td>
              <td><%= homework.due_at.strftime("%m-%d-%Y") %></td>
              <td><%= link_to "view", teacher_homework_path(homework) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
<% end %>

app/views/teacher/homeworks/new.html.erb
<h1>New Homework</h1>

<div class="row">
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <%= simple_form_for @homework, url: teacher_homeworks_path do |f| %>
      <%= f.input :title %>
      <%= f.input :question, input_html: { rows: 7 } %>
      <%= f.input :due_at, as: :date_time_picker %>
      <%= f.button :submit, class: "pull-right btn-success" %>
      <%= link_to "Back", teacher_homeworks_path, class: "btn btn-default pull-left" %>
    <% end %>
  </div><!-- .col-lg-6 .col-md-6 .col-sm-12 .col-xs-12 -->
</div><!-- .row -->

app/views/teacher/homeworks/show.html.erb
<%= render partial: "shared/flash_messages", flash: flash %>

<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">

    <%= link_to "Back", teacher_homeworks_path, class: "btn btn-default btn-block margin-bottom-20" %>

    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= @homework.title %></h3>
        <h5>Question: <%= @homework.question %></h5>
      </div><!-- .panel-body -->
    </div><!-- .panel .panel-default -->

    <% unless @homework.expired? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          Which student should submit this homework?
        </div><!-- .panel-heading -->
        <% if @unassigned_students.empty? %>
          <div class="panel-body">
            <h4 class="empty-state">No students left to assign this homework.</h4>
          </div>
        <% else %>
          <table class="table table-striped">
            <tbody>
              <% @unassigned_students.each do |student| %>
                <tr>
                  <td><%= student.username %></td>
                  <td>
                    <%= simple_form_for Assignment.new, url: teacher_homework_assignments_path(@homework) do |f| %>
                      <%= f.input :user_id, as: :hidden, input_html: { value: student.id } %>
                      <%= f.button :submit, "assign", class: "link" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div><!-- .panel .panel-default -->
    <% end %>

  </div><!-- .col-lg-3 .col-md-3 .col-sm-6 .col-xs-12 -->

  <div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Already assigned students
      </div><!-- .panel-heading -->
      <% if @assignments.empty? %>
        <div class="panel-body">
          <h4 class="empty-state">You haven't assigned this homework to a student yet! Just go ahead and select a few on the left.</h4>
        </div>
      <% else %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Student Name</th>
              <th>Latest Answer</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @assignments.each do |assignment| %>
              <tr>
                <td><%= assignment.student.username %></td>
                <td>
                  <% if assignment.answers.empty? %>
                    <strong>No submissions for this homework yet</strong>
                  <% else %>
                    <%= assignment.answers.first.text %>
                  <% end %>
                </td>
                <td><%= link_to "all answers", teacher_homework_assignment_path(assignment.homework, assignment) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div><!-- .panel .panel-default -->
  </div><!-- .col-lg-9 .col-md-9 .col-sm-6 .col-xs-12 -->
</div><!-- .row -->