config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :create]

  namespace :teacher do
    resources :homeworks do
      resources :assignments, only: [:create, :show]
    end
  end

  namespace :student do
    resources :assignments, only: [:index] do
      resources :answers, only: [:new, :create]
    end
  end

  root 'teacher/homeworks#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id            :integer          not null, primary key
#  assignment_id :integer          not null
#  text          :text             not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Answer < ActiveRecord::Base
  belongs_to :assignment, counter_cache: true

  validates :text, presence: true
end

app/controllers/student/answers_controller.rb
class Student::AnswersController < ApplicationController

  before_action :authenticate_student!

  def new
    @assignment = current_student.assignments.find(params[:assignment_id])
    @answer = Answer.new

    if @assignment.homework.expired?
      flash[:alert] = "Ops! You missed this assignment's deadline, sorry :("
      redirect_to student_assignments_path
    end    
  end

  def create
    @assignment = current_student.assignments.find(params[:assignment_id])
    @answer = @assignment.answers.new(answer_params)

    if @assignment.homework.expired?
      flash[:alert] = "Ops! You missed this assignment's deadline, sorry :("
      redirect_to student_assignments_path
    elsif @answer.save
      flash[:notice] = "Good job, answer submited!"
      redirect_to student_assignments_path
    else
      render :new
    end
      
  end

  private

    def answer_params
      params.require(:answer).permit(:text)
    end
end

app/controllers/student/assignments_controller.rb
class Student::AssignmentsController < ApplicationController

  before_action :authenticate_student!

  def index
    @current_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at::date >= ?", Date.current)
                              .order("answers_count, homeworks.due_at")
    @past_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at::date < ?", Date.current)
                              .order("answers_count, homeworks.due_at")
  end
end

app/controllers/student/homeworks_controller.rb
class Student::HomeworksController < ApplicationController

  before_action :authenticate_student!

  def index
    @current_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at >= ?", Date.current.end_of_day)
    @past_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at < ?", Date.current.end_of_day)
  end
end

app/views/student/answers/new.html.erb
<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">

    <%= link_to "Back", student_assignments_path, class: "btn btn-default btn-block margin-bottom-20" %>

    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= @assignment.homework.title %></h3>
        <h5>Question: <%= @assignment.homework.question %></h5>
      </div><!-- .panel-body -->
    </div><!-- .panel .panel-default -->

  </div><!-- .col-lg-3 col-md-3 col-sm-6 col-xs-12 -->

  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <%= simple_form_for @answer, url: student_assignment_answers_path do |f| %>
      <%= f.input :text, input_html: { rows: 10 } %>
      <%= f.button :submit, "Submit Answer", class: "btn-success pull-right" %>
    <% end %>
  </div><!-- .col-lg-3 .col-md-3 .col-sm-6 .col-xs-12 -->
</div><!-- .row -->