config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :create]

  namespace :teacher do
    resources :homeworks do
      resources :assignments, only: [:create, :show]
    end
  end

  namespace :student do
    resources :assignments, only: [:index] do
      resources :answers, only: [:new, :create]
    end
  end

  root 'teacher/homeworks#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]
end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  homework_id :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Assignment < ActiveRecord::Base
  belongs_to :student, class_name: "User", foreign_key: "user_id"
  belongs_to :homework
  has_many :answers, -> { order(created_at: :desc) }
end

app/controllers/student/answers_controller.rb
class Student::AnswersController < ApplicationController

  before_action :authenticate_student!

  def new
    @assignment = current_student.assignments.find(params[:assignment_id])
    @answer = Answer.new

    if @assignment.homework.expired?
      flash[:alert] = "Ops! You missed this assignment's deadline, sorry :("
      redirect_to student_assignments_path
    end    
  end

  def create
    @assignment = current_student.assignments.find(params[:assignment_id])
    @answer = @assignment.answers.new(answer_params)

    if @assignment.homework.expired?
      flash[:alert] = "Ops! You missed this assignment's deadline, sorry :("
      redirect_to student_assignments_path
    elsif @answer.save
      flash[:notice] = "Good job, answer submited!"
      redirect_to student_assignments_path
    else
      render :new
    end
      
  end

  private

    def answer_params
      params.require(:answer).permit(:text)
    end
end

app/controllers/student/assignments_controller.rb
class Student::AssignmentsController < ApplicationController

  before_action :authenticate_student!

  def index
    @current_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at::date >= ?", Date.current)
                              .order("answers_count, homeworks.due_at")
    @past_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at::date < ?", Date.current)
                              .order("answers_count, homeworks.due_at")
  end
end

app/controllers/student/homeworks_controller.rb
class Student::HomeworksController < ApplicationController

  before_action :authenticate_student!

  def index
    @current_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at >= ?", Date.current.end_of_day)
    @past_assignments = current_student.assignments.joins(:homework)
                              .includes(:homework).where("due_at < ?", Date.current.end_of_day)
  end
end

app/controllers/teacher/assignments_controller.rb
class Teacher::AssignmentsController < ApplicationController

  before_action :authenticate_teacher!

  def show
    @assignment = current_teacher.homeworks.find(params[:homework_id]).assignments.find(params[:id])
  end

  def create
    @homework = current_teacher.homeworks.find(params[:homework_id])
 
    @assignment = @homework.assignments.new(assignment_params)

    if @assignment.save
      flash[:notice] = "Student successfully assigned to homework"
      redirect_to teacher_homework_path(@homework)
    else
      render :new
    end
  end

  private

    def assignment_params
      params.require(:assignment).permit(:user_id)
    end
end

app/views/student/assignments/index.html.erb
<%= render partial: "shared/flash_messages", flash: flash %>

<div class="panel panel-default">
  <div class="panel-heading">
    Current homeworks
  </div>

  <% if @current_assignments.empty? %>
    <div class="panel-body">
      <h4 class="empty-state">Ops, you don't have any assigned homeworks for now. Go ask your teacher for some work :)</h4>
    </div>
  <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Homework</th>
          <th>Due date</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @current_assignments.each do |assignment| %>
          <tr>
            <td><%= assignment.homework.title %></td>
            <td><%= assignment.homework.due_at.strftime("%m-%d-%Y") %></td>
            <td>
              <%= link_to "submit answer", new_student_assignment_answer_path(assignment) %>
            </td>
            <td>
              <% if assignment.answers_count.zero? %>
                <span class="label label-warning pull-right">Please answer me</span>
              <% else %>
                <span class="label label-success pull-right">Yay! Already submited</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<% unless @past_assignments.empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      Past homeworks
    </div>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Homework</th>
            <th>Due date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @past_assignments.each do |assignment| %>
            <tr>
              <td><%= assignment.homework.title %></td>
              <td>
                <%= assignment.homework.due_at.strftime("%m-%d-%Y") %>
              </td>
              <td>
                <% if assignment.answers_count.zero? %>
                  <span class="label label-danger pull-right">Sorry, you missed this one</span>
                <% else %>
                  <span class="label label-success pull-right">Be cool, you submited this one</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
<% end %>