config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :create]

  namespace :teacher do
    resources :homeworks do
      resources :assignments, only: [:create, :show]
    end
  end

  namespace :student do
    resources :assignments, only: [:index] do
      resources :answers, only: [:new, :create]
    end
  end

  root 'teacher/homeworks#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avengers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Avengers", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Homework", root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign out", logout_path %></li>
            <li><%= link_to "Manage users", users_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avengers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="sign-in">

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/sessions_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avengers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="sign-in">

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avengers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    
    <div class="navbar-header">
      <%= link_to "Avengers", login_path, class: "navbar-brand" %>
    </div>

  </div><!-- /.container -->
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>